version: '3.4'

services:
  catalogdb:
    image: postgres 

  loki:
    image: grafana/loki

  grafana:
    image: grafana/grafana

  jaeger:
    image: jaegertracing/all-in-one

  prometheus:
    image: prom/prometheus

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  load.test:
    image: ${DOCKER_REGISTRY-}loadtest
    build:
      context: .
      dockerfile: LoadTests/K6LoadTests/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
