version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce

  catalogdb:
    image: postgres

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  loki:
    image: grafana/loki

  grafana:
    image: grafana/grafana

  jaeger:
    image: jaegertracing/all-in-one

  prometheus:
    image: prom/prometheus

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  portainer_data:
