services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalogdb:
    container_name: catalogdb
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_catalog:/var/lib/postgresql/data/ 

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/ 
  
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  loki:
    container_name: loki
    ports:
      - "3100:3100"

  grafana:
    ports:
      - "3000:3000"

  jaeger:
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14250:14250"
      - "6831:6831/udp"
      - "4317:4317"
      - "14268:14268"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    container_name: prometheus
    ports:
      - "9090:9090"
    environment : 
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://0.0.0.0:9090/api/v1/otlp/v1/metrics
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    command:
      - --enable-feature=otlp-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  load.test:
     ports:
      - "3001:3001"
     depends_on:
      - basket.api
  
  chaos.engineering:
     ports:
      - "3002:3001"
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     depends_on:
      - basket.api

  catalog.api:
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - Serilog__WriteTo__1__Args__uri=http://loki:3100
      - OtelTrace__Endpoint=http://jaeger:4317
      - OtelMetric__Endpoint=http://prometheus:9090/api/v1/otlp/v1/metrics
    depends_on:
      - catalogdb
      - loki 
      - jaeger
      - prometheus 
    ports:
      - "6000:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - Serilog__WriteTo__1__Args__uri=http://loki:3100
      - OtelTrace__Endpoint=http://jaeger:4317
      - OtelMetric__Endpoint=http://prometheus:9090/api/v1/otlp/v1/metrics
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
    ports:
      - "6001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Data Source=discountdb
      - Serilog__WriteTo__1__Args__uri=http://loki:3100
      - OtelTrace__Endpoint=http://jaeger:4317
      - OtelMetric__Endpoint=http://prometheus:9090/api/v1/otlp/v1/metrics
    ports:
      - "6002:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro